# Generated by Django 4.0.2 on 2022-02-25 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='emp',
            fields=[
                ('eid', models.IntegerField(primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=20)),
                ('esal', models.DecimalField(decimal_places=2, max_digits=6)),
                ('edno', models.IntegerField()),
            ],
        ),
    ]
