# Generated by Django 4.0.2 on 2022-02-19 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('cnumber', models.IntegerField(primary_key=True, serialize=False)),
                ('cbrand', models.CharField(max_length=30)),
                ('ctype', models.CharField(max_length=20)),
                ('cowner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app19.owner')),
            ],
        ),
    ]
