# Generated by Django 4.0.2 on 2022-02-18 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sid', models.IntegerField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=20)),
                ('sadd', models.CharField(max_length=30)),
                ('sfee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sstatus', models.BooleanField(default=False)),
            ],
        ),
    ]
