# Generated by Django 4.0.2 on 2022-03-01 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('cname', models.CharField(max_length=20)),
                ('cadd', models.CharField(max_length=30)),
                ('eid', models.IntegerField(primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
