# Generated by Django 4.0.2 on 2022-02-24 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('cid', models.IntegerField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=20)),
                ('cadd', models.CharField(max_length=30)),
                ('payment', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
